version: '3'

services:
  central:
    build:
      context: .
      dockerfile: ./Dockerfile.central
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  connection:
    build:
      context: .
      dockerfile: ./Dockerfile.connection
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
